version: '3.8'

services:
  nginx:
    image: nginx:1.29.0
    container_name: nginx-server-1.29.0
    deploy:
      resources:
        # 硬性限制（容器最多能使用的资源）
        limits:
          cpus: '0.5'       # 最多 0.5 个 CPU 核心
          memory: 256M      # 最多 256MB 内存
        # 软性预留（保证容器至少能获得的资源）
        reservations:
          cpus: '0.25'       # 至少预留 0.25 个 CPU 核心
          memory: 128M      # 至少预留 128MB 内存
    # 绑定到特定 CPU 核心（可选）
    cpuset: "1"  # "0,1" 仅允许使用主机的 0 和 1 号核心
    restart: always
    ports:
      - "80:80"    # HTTP 端口映射
      - "443:443"  # HTTPS 端口映射（如需使用 SSL 证书）
    volumes:
      - ./conf.d:/etc/nginx/conf.d        # Nginx 配置文件目录
      # - ./nginx/ssl:/etc/nginx/ssl            # SSL 证书目录（可选）
      # - ./nginx/logs:/var/log/nginx           # 日志目录
      - ./html:/usr/share/nginx/html    # 网站根目录
    environment:
      - TZ=Asia/Shanghai                      # 设置时区为上海
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
